import pandas as pd
import requests

header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

url = "https://www.terra.com.br/esportes/futebol/copa-2022/tabela/"
    
r = requests.get(url, headers=header)   

dfs = pd.read_html(r.text)

print(dfs.match)
# 
# print('GRUPO A')
# print(dfs[0]['Times.2'])
# print(dfs[0]['P'])
# print(dfs[0]['J'])
# print(dfs[0]['V'])
# print(dfs[0]['E'])
# print(dfs[0]['D'])
# print(dfs[0]['GP'])
# print(dfs[0]['GC'])
# print(dfs[0]['SG'])
# print(dfs[0]['%'])
# 
# print('GRUPO B')
# print(dfs[1]['Times.2'])
# print(dfs[1]['P'])
# print(dfs[1]['J'])
# print(dfs[1]['V'])
# print(dfs[1]['E'])
# print(dfs[1]['D'])
# print(dfs[1]['GP'])
# print(dfs[1]['GC'])
# print(dfs[1]['SG'])
# print(dfs[1]['%'])
# 
# print('GRUPO C')
# print(dfs[2]['Times.2'])
# print(dfs[2]['P'])
# print(dfs[2]['J'])
# print(dfs[2]['V'])
# print(dfs[2]['E'])
# print(dfs[2]['D'])
# print(dfs[2]['GP'])
# print(dfs[2]['GC'])
# print(dfs[2]['SG'])
# print(dfs[2]['%'])
# 
# print('GRUPO D')
# print(dfs[3]['Times.2'])
# print(dfs[3]['P'])
# print(dfs[3]['J'])
# print(dfs[3]['V'])
# print(dfs[3]['E'])
# print(dfs[3]['D'])
# print(dfs[3]['GP'])
# print(dfs[3]['GC'])
# print(dfs[3]['SG'])
# print(dfs[3]['%'])
# 
# print('GRUPO E')
# print(dfs[4]['Times.2'])
# print(dfs[4]['P'])
# print(dfs[4]['J'])
# print(dfs[4]['V'])
# print(dfs[4]['E'])
# print(dfs[4]['D'])
# print(dfs[4]['GP'])
# print(dfs[4]['GC'])
# print(dfs[4]['SG'])
# print(dfs[4]['%'])
# 
# print('GRUPO F')
# print(dfs[5]['Times.2'])
# print(dfs[5]['P'])
# print(dfs[5]['J'])
# print(dfs[5]['V'])
# print(dfs[5]['E'])
# print(dfs[5]['D'])
# print(dfs[5]['GP'])
# print(dfs[5]['GC'])
# print(dfs[5]['SG'])
# print(dfs[5]['%'])
# 
# print('GRUPO G')
# print(dfs[6]['Times.2'])
# print(dfs[6]['P'])
# print(dfs[6]['J'])
# print(dfs[6]['V'])
# print(dfs[6]['E'])
# print(dfs[6]['D'])
# print(dfs[6]['GP'])
# print(dfs[6]['GC'])
# print(dfs[6]['SG'])
# print(dfs[6]['%'])
# 
# print('GRUPO H')
# print(dfs[7]['Times.2'])
# print(dfs[7]['P'])
# print(dfs[7]['J'])
# print(dfs[7]['V'])
# print(dfs[7]['E'])
# print(dfs[7]['D'])
# print(dfs[7]['GP'])
# print(dfs[7]['GC'])
# print(dfs[7]['SG'])
# print(dfs[7]['%'])